In [5]:
import pandas as pd
import holidays
from datetime import datetime, timedelta

In [3]:
df = pd.read_csv('../data/combined_data.csv',index_col=None)

In [4]:
df

,toll_date,toll_hour,toll_10_minute_block,minute_of_hour,hour_of_day,day_of_week_int,day_of_week,toll_week,time_period,vehicle_class,detection_group,detection_region,crz_entries,excluded_roadway_entries
0,2026-06-26T00:00:00.000,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,West 60th St,West 60th St,148,0
1,2026-06-26T00:00:00.000,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,West Side Highway at 60th St,West Side Highway,119,0
2,2026-06-26T00:00:00.000,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Holland Tunnel,New Jersey,132,0
3,2026-06-26T00:00:00.000,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Queens Midtown Tunnel,Queens,132,0
4,2026-06-26T00:00:00.000,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Queensboro Bridge,Queens,73,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6168851,2026-08-22T00:00:00.000,2026-08-22T23:00:00.000,2026-08-22T23:50:00.000,50,23,7,Saturday,2026-08-16T00:00:00.000,Overnight,TLC Taxi/FHV,Lincoln Tunnel,New Jersey,69,0
6168852,2026-08-22T00:00:00.000,2026-08-22T23:00:00.000,2026-08-22T23:50:00.000,50,23,7,Saturday,2026-08-16T00:00:00.000,Overnight,TLC Taxi/FHV,Queens Midtown Tunnel,Queens,130,0
6168853,2026-08-22T00:00:00.000,2026-08-22T23:00:00.000,2026-08-22T23:50:00.000,50,23,7,Saturday,2026-08-16T00:00:00.000,Overnight,TLC Taxi/FHV,Queensboro Bridge,Queens,81,0
6168854,2026-08-22T00:00:00.000,2026-08-22T23:00:00.000,2026-08-22T23:50:00.000,50,23,7,Saturday,2026-08-16T00:00:00.000,Overnight,TLC Taxi/FHV,West 60th St,West 60th St,122,0
6168855,2026-08-22T00:00:00.000,2026-08-22T23:00:00.000,2026-08-22T23:50:00.000,50,23,7,Saturday,2026-08-16T00:00:00.000,Overnight,TLC Taxi/FHV,West Side Highway at 60th St,West Side Highway,82,0

In [6]:
df['toll_date'] = pd.to_datetime(df['toll_date'])
df['hour_of_day'] = pd.to_numeric(df['hour_of_day'])
df['minute_of_hour'] = pd.to_numeric(df['minute_of_hour'])
df['crz_entries'] = pd.to_numeric(df['crz_entries'])

In [7]:
df.head()

,toll_date,toll_hour,toll_10_minute_block,minute_of_hour,hour_of_day,day_of_week_int,day_of_week,toll_week,time_period,vehicle_class,detection_group,detection_region,crz_entries,excluded_roadway_entries
0,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,West 60th St,West 60th St,148,0
1,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,West Side Highway at 60th St,West Side Highway,119,0
2,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Holland Tunnel,New Jersey,132,0
3,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Queens Midtown Tunnel,Queens,132,0
4,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Queensboro Bridge,Queens,73,0

In [10]:
us_holidays = holidays.US()

df['holiday_ind'] = df['toll_date'].apply(
    lambda x: x in us_holidays
).astype(int)

In [11]:
df[df['toll_date']=='2026-07-04']

,toll_date,toll_hour,toll_10_minute_block,minute_of_hour,hour_of_day,day_of_week_int,day_of_week,toll_week,time_period,vehicle_class,detection_group,detection_region,crz_entries,excluded_roadway_entries,holiday_ind
5650456,2026-07-04,2026-07-04T00:00:00.000,2026-07-04T00:00:00.000,0,0,7,Saturday,2026-06-28T00:00:00.000,Overnight,"1 - Cars, Pickups and Vans",Brooklyn Bridge,Brooklyn,56,87,1
5650457,2026-07-04,2026-07-04T00:00:00.000,2026-07-04T00:00:00.000,0,0,7,Saturday,2026-06-28T00:00:00.000,Overnight,"1 - Cars, Pickups and Vans",Hugh L. Carey Tunnel,Brooklyn,19,9,1
5650458,2026-07-04,2026-07-04T00:00:00.000,2026-07-04T00:00:00.000,0,0,7,Saturday,2026-06-28T00:00:00.000,Overnight,"1 - Cars, Pickups and Vans",Manhattan Bridge,Brooklyn,85,0,1
5650459,2026-07-04,2026-07-04T00:00:00.000,2026-07-04T00:00:00.000,0,0,7,Saturday,2026-06-28T00:00:00.000,Overnight,"1 - Cars, Pickups and Vans",Williamsburg Bridge,Brooklyn,106,0,1
5650460,2026-07-04,2026-07-04T00:00:00.000,2026-07-04T00:00:00.000,0,0,7,Saturday,2026-06-28T00:00:00.000,Overnight,"1 - Cars, Pickups and Vans",East 60th St,East 60th St,152,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660819,2026-07-04,2026-07-04T23:00:00.000,2026-07-04T23:50:00.000,50,23,7,Saturday,2026-06-28T00:00:00.000,Overnight,TLC Taxi/FHV,Lincoln Tunnel,New Jersey,55,0,1
5660820,2026-07-04,2026-07-04T23:00:00.000,2026-07-04T23:50:00.000,50,23,7,Saturday,2026-06-28T00:00:00.000,Overnight,TLC Taxi/FHV,Queens Midtown Tunnel,Queens,142,0,1
5660821,2026-07-04,2026-07-04T23:00:00.000,2026-07-04T23:50:00.000,50,23,7,Saturday,2026-06-28T00:00:00.000,Overnight,TLC Taxi/FHV,Queensboro Bridge,Queens,71,0,1
5660822,2026-07-04,2026-07-04T23:00:00.000,2026-07-04T23:50:00.000,50,23,7,Saturday,2026-06-28T00:00:00.000,Overnight,TLC Taxi/FHV,West 60th St,West 60th St,125,0,1
5660823,2026-07-04,2026-07-04T23:00:00.000,2026-07-04T23:50:00.000,50,23,7,Saturday,2026-06-28T00:00:00.000,Overnight,TLC Taxi/FHV,West Side Highway at 60th St,West Side Highway,69,0,1

In [12]:
df.head()

,toll_date,toll_hour,toll_10_minute_block,minute_of_hour,hour_of_day,day_of_week_int,day_of_week,toll_week,time_period,vehicle_class,detection_group,detection_region,crz_entries,excluded_roadway_entries,holiday_ind
0,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,West 60th St,West 60th St,148,0,0
1,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,West Side Highway at 60th St,West Side Highway,119,0,0
2,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Holland Tunnel,New Jersey,132,0,0
3,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Queens Midtown Tunnel,Queens,132,0,0
4,2026-06-26,2026-06-26T23:00:00.000,2026-06-26T23:50:00.000,50,23,6,Friday,2026-06-21T00:00:00.000,Overnight,TLC Taxi/FHV,Queensboro Bridge,Queens,73,0,0

In [19]:
df['overnight_ind'] = df['time_period'].apply(
    lambda x: 1 if x == 'Overnight' else 0
).astype(int)

In [14]:
df['toll_date'].max()

Timestamp('2026-08-22 00:00:00')

In [21]:
df['vehicle_class'].value_counts()

vehicle_class
2 - Single-Unit Trucks        1028151
5 - Motorcycles               1028146
TLC Taxi/FHV                  1028144
1 - Cars, Pickups and Vans    1028144
3 - Multi-Unit Trucks         1028140
4 - Buses                     1028131
Name: count, dtype: int64

In [24]:
vehicle_map = {
    'TLC Taxi/FHV':0,
    '1 - Cars, Pickups and Vans':1,
    '2 - Single-Unit Trucks':2,
    '3 - Multi-Unit Trucks':3,
    '4 - Buses':4,
    '5 - Motorcycles':5
}

df['vehicle_category'] = df['vehicle_class'].map(vehicle_map)

In [32]:
df['detection_region'].value_counts()

detection_region
Brooklyn             2056287
Queens               1028146
New Jersey           1028136
West Side Highway     514074
FDR Drive             514072
West 60th St          514071
East 60th St          514070
Name: count, dtype: int64

In [31]:
df['detection_group'].value_counts()

detection_group
West Side Highway at 60th St    514074
Queens Midtown Tunnel           514074
Manhattan Bridge                514074
Queensboro Bridge               514072
FDR Drive at 60th St            514072
West 60th St                    514071
Hugh L. Carey Tunnel            514071
Williamsburg Bridge             514071
Brooklyn Bridge                 514071
East 60th St                    514070
Lincoln Tunnel                  514070
Holland Tunnel                  514066
Name: count, dtype: int64

In [34]:
df[['detection_region','detection_group']].value_counts().sort_index()

detection_region   detection_group
Brooklyn           Brooklyn Bridge                 514071
                   Hugh L. Carey Tunnel            514071
                   Manhattan Bridge                514074
                   Williamsburg Bridge             514071
East 60th St       East 60th St                    514070
FDR Drive          FDR Drive at 60th St            514072
New Jersey         Holland Tunnel                  514066
                   Lincoln Tunnel                  514070
Queens             Queens Midtown Tunnel           514074
                   Queensboro Bridge               514072
West 60th St       West 60th St                    514071
West Side Highway  West Side Highway at 60th St    514074
Name: count, dtype: int64

In [44]:
region_mapping = {
    'Brooklyn':1,
    'Queens':2,
    'New Jersey':3,
    'West Side Highway':4,
    'FDR Drive':5,
    'West 60th St':6,
    'East 60th St':7
}

group_mapping = {
    'Brooklyn Bridge':1,
    'Hugh L. Carey Tunnel':2,
    'Williamsburg Bridge':3,
    'Manhattan Bridge':4,
    'Queensboro Bridge':5,
    'Queens Midtown Tunnel':6,
    'Holland Tunnel':7,
    'Lincoln Tunnel':8,
    'West Side Highway at 60th St':9,
    'FDR Drive at 60th St':10,
    'West 60th St':11,
    'East 60th St':12
}

In [46]:
df['region_id'] = df['detection_region'].map(region_mapping).fillna(0).astype(int)
df['group_id'] = df['detection_group'].map(group_mapping).fillna(0).astype(int)

In [49]:
df.head(2)

,toll_date,toll_hour,toll_10_minute_block,minute_of_hour,hour_of_day,day_of_week_int,day_of_week,toll_week,time_period,vehicle_class,detection_group,detection_region,crz_entries,excluded_roadway_entries,holiday_ind,overnight_ind,vehicle_category,region_id,group_id
5577827,2025-01-05,2025-01-05T00:00:00.000,2025-01-05T00:00:00.000,0,0,1,Sunday,2025-01-05T00:00:00.000,Overnight,5 - Motorcycles,FDR Drive at 60th St,FDR Drive,0,0,0,1,5,5,10
5577828,2025-01-05,2025-01-05T00:00:00.000,2025-01-05T00:00:00.000,0,0,1,Sunday,2025-01-05T00:00:00.000,Overnight,5 - Motorcycles,East 60th St,East 60th St,3,0,0,1,5,7,12

In [42]:
df = df.sort_values("toll_10_minute_block")

In [ ]:
# We want total volume on roadways regardless of whether or not they stayed out of the CRZ
df["traffic_volume"] = (
    df["crz_entries"].fillna(0) +
    df["excluded_roadway_entries"].fillna(0)
)

In [ ]:
df.drop(['day_of_week','toll_hour','minute_of_hour','hour_of_day','toll_date','crz_entries','excluded_roadway_entries',
         'day_of_week','toll_week','vehicle_class','time_period','detection_group','detection_region'], inplace=True, axis=1)

In [62]:
data = df.groupby(
    [
        "toll_10_minute_block",
        "day_of_week_int",
        "holiday_ind",
        "overnight_ind",
        "region_id",
        "group_id"
    ],
    as_index=False
).agg(traffic_volume=("traffic_volume", "sum"))

In [64]:
data["toll_10_minute_block"] = pd.to_datetime(
    data["toll_10_minute_block"]
)

data = data.sort_values(
    ["group_id", "toll_10_minute_block"]
).reset_index(drop=True)

In [65]:
data

,toll_10_minute_block,day_of_week_int,holiday_ind,overnight_ind,region_id,group_id,traffic_volume
0,2025-01-05 00:00:00,1,0,1,1,1,317
1,2025-01-05 00:10:00,1,0,1,1,1,330
2,2025-01-05 00:20:00,1,0,1,1,1,300
3,2025-01-05 00:30:00,1,0,1,1,1,316
4,2025-01-05 00:40:00,1,0,1,1,1,308
...,...,...,...,...,...,...,...
1028155,2026-08-22 23:10:00,7,0,1,7,12,523
1028156,2026-08-22 23:20:00,7,0,1,7,12,452
1028157,2026-08-22 23:30:00,7,0,1,7,12,488
1028158,2026-08-22 23:40:00,7,0,1,7,12,481
1028159,2026-08-22 23:50:00,7,0,1,7,12,468

In [ ]:
# check for gaps (ideally none)
data["time_diff"] = (
    data.groupby("group_id")["toll_10_minute_block"]
        .diff()
)

bad_intervals = data[
    data["time_diff"].notna() &
    (data["time_diff"] != pd.Timedelta(minutes=10))
]

bad_intervals[
    ["group_id", "toll_10_minute_block", "time_diff"]
].head(50)

In [ ]:
# check for duplicates (ideally none)
data.duplicated(
    subset=["group_id", "toll_10_minute_block"]
).sum()

np.int64(0)

In [73]:
data.drop('time_diff', axis=1, inplace=True)

In [71]:
# cyclical encoding for days of week
data["dow_sin"] = np.sin(
    2 * np.pi * data["day_of_week_int"] / 7
)

data["dow_cos"] = np.cos(
    2 * np.pi * data["day_of_week_int"] / 7
)

In [74]:
data.to_csv('../data/processed_data.csv', index=False)